// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "rememBear",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "rememBear",
            targets: ["AppModule"],
            bundleIdentifier: "Apple-Developer-Academy.bring-teddy-life",
            teamIdentifier: "A84HQ97N4T",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            capabilities: [
                .camera(purposeString: "Our app will ask access to your camera for AR experience. Please allow."),
                .speechRecognition(purposeString: "Our app will ask access to use speech recognition. Please allow."),
                .microphone(purposeString: "Our app will ask access to use microphone. Please allow.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)